#!/bin/sh
set -eu
umask 077

if [ "$(/usr/bin/id -u)" -ne 0 ]; then
  echo "protected publisher must run as root" >&2
  exit 1
fi

root=/opt/noetic-dev-main-publisher
release=$(/usr/bin/readlink -f "$root/current")
case "$release" in
  "$root"/releases/[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]) ;;
  *)
    echo "protected publisher release is invalid" >&2
    exit 1
    ;;
esac
exec /usr/bin/env -i PATH=/usr/bin:/bin HOME=/root \
  /usr/bin/python3 -I "$release/scripts/governance/promote_main.py" "$@"
